# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Logperience"
description: > # this means to ignore newlines until "email:"
   a log of my XP

email: arunkumarsundaramurthy@gmail.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/keyboard.jpg"

name: 'Arun Kumar Sundaramurthy'
author: 'Arun Kumar Sundaramurthy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.arunks.me/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/arunkumarmurthy
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: linkedin
    url:  https://in.linkedin.com/in/arunkumarsundaramurthy
    desc: Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon: github
    url:  https://github.com/arunkumarsundaramurthy
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	facebook
    url:	https://www.facebook.com/Arunkumarsundaramurthy
    desc: Connect with me on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	google-plus
    url:	https://plus.google.com/+ArunKumarSundaramurthy/
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
